//
// Created by childcity on 05.02.20.
//

#ifndef LEARNMULTITHREADC_MYTHREADSAFEQUEUE_HPP
#define LEARNMULTITHREADC_MYTHREADSAFEQUEUE_HPP


template <class T>
struct MyThreadSafeQueue {

};


#endif //LEARNMULTITHREADC_MYTHREADSAFEQUEUE_HPP
